### ISSUE TITLE
Informacja, błąd, potwierdzenie

### ISSUE THREAD

**Issue by logeen** [logeen/forumweb#10]
- **message_body.tpl** - Informacja: http://www.forumweb.pl/viewforum.php?f=-1
- **error_body.tpl** - błąd: np. próba wysłania prywatnej wiadomości do nieistniejącego użytkownika
- **confirm_body.tpl** - Potwierdzenie: np. przed usunięcie prywatnej wiadomości

**Comment by KacperKozak** [comment]
e82227dea591ae096e52055c3d800365343b6c86

**Comment by logeen** [comment]
- Objąć cała zawartość plików div-ami z klasami odpowiednio: message_body-tpl, error_body-tpl, confirm_body-tpl.
- Treść komunikatu nie może się zawierać w `p`, ponieważ trafiają się tutaj elementy blokowe.
- Skąd nazwa klasy "notification"? Proponuję zamienić na "message", bo "notification" może być potrzebne do licznika powiadomień.
- Zamienić "breadcrumb" na:

``` html
<nav class="breadcrumb">
    <ul>
        <li><a href="{U_INDEX}">{L_INDEX}</a></li> 
    </ul>
</nav>
```

**Comment by KacperKozak** [comment]
a61b6cc71e65cecbb26d83d6ee8c0b8686933e44
