### ISSUE TITLE
Szybka odpowiedź

### ISSUE THREAD

**Issue by logeen** [logeen/forumweb#15]
**quick_reply.tpl** - Szybka odpowiedź: http://www.forumweb.pl/viewtopic.php?t=2895

Ten plik jest używany również przy edycji odpowiedzi na prywatną wiadomośś, a nie tylko przy wysyłaniu odpowiedzi do tematu.

---

UWAGA: Wykorzystać kod JS edytora wykonany w zadaniu #7

**Comment by Kwpolska** [comment]
sugerowalbym przekopiowac wiekszosc z #7.

**Comment by Comandeer** [comment]
aha, wygląda na to, że to się nie odświeża - uparcie wyświetla wersję tabelkową mimo, że kod jest zmieniony

**Comment by logeen** [comment]
Poprawione. Dzięki za informację o błędzie w API.
