### ISSUE TITLE
Strona Główna

### ISSUE THREAD

**Issue by logeen** [logeen/forumweb#2]
**index_body.tpl** - Strona Główna: http://www.forumweb.pl/index.php

---

UWAGA: Należy zwrócić uwagę, że układ listy tematów forum jest podobny jak układ forów na stronie głównej, a więc kod HTML powinien być spójny do zadania #3

**Comment by Kwpolska** [comment]
dlaczego na githubie widac krzaki w tym pliku?  czyzby github nie potrafił iso-numerków?

**Comment by logeen** [comment]
Możliwe, ale to raczej nie ma znaczenia. W kodzie plików szablonów nie powinno być żadnych polskich tekstów - wszystko powinno przychodzić w danych szablonu. W tej chwili, z tego co widzę, polskie znaki są w tymczasowym komentarzu (btw: tak, w kodzie HTML nie ma prawa być żadnych obrazków poza awatarami i wstawionymi w treści postów - wszystko resztę w czystym CSS).

**Comment by Comandeer** [comment]
no choinka, to zaś usuwać obrazki ;)
i tak - github nie radzi sobie z ISO, jest nastawiony na UTF-8

**Comment by logeen** [comment]
Nie tyle usuwać, co zastępować klasami CSS. Żaden element nie powinien ostatecznie zniknąć ze strony. Dopóki obrazek jest dodawany na sztywno zawsze taki sam, klasę CSS można podać wprost. Ale w niektórych przypadkach w jednym miejscu mogą się pojawić różne obrazki - np. folder "przeczytane"/"nieprzeczytane" itp. Jeśli gdzieś obecnie jest obrazek i trzeba go zamienić na jakiś _image replacement_, a odpowiednia klasa na to nie przychodzi w danych szablonu, to dajcie znać, a ją dodam.

Poza tym w danych szablonu dla wszystkich obrazków powinny przychodzić alternatywne wersje tekstowe - z ich pomocą właśnie należy zrobić _image replacement_. Jeśli do jakiegoś obrazka nie przychodzi w danych alternatywna tekstowa, proszę o informację, to ją dodam.

**Comment by logeen** [comment]
Przykład o co mi chodzi. Taki kod:

``` html
<img src="{catrow.forumrow.FORUM_FOLDER_IMG}"    alt="{catrow.forumrow.L_FORUM_FOLDER_ALT}" title="{catrow.forumrow.L_FORUM_FOLDER_ALT}">
```

można w całości zastąpić na:

``` html
<span class="{catrow.forumrow.FORUM_FOLDER_CLASS}" title="{catrow.forumrow.L_FORUM_FOLDER_ALT}">{catrow.forumrow.L_FORUM_FOLDER_ALT}</span>
```

Ale nie można go od po prostu od tak usunąć. Potem w CSS nie będzie się dało nadać mu tła na sztywno właśnie dlatego, że w tym miejscu mogą się pojawić różne obrazki folderów (przeczytane/nieprzeczytane). Poza tym sam tekst `L_FORUM_FOLDER_ALT` powinien być dostępny w źródle - np. dla osób niewidomych, botów czy innych skórek, które będą chciały go wyświetlić na ekranie zamiast zamieniać na obrazek.

**Comment by Comandeer** [comment]
to właśnie  o coś takiego mniej więcej chodziło - taki skrót myślowy ;)
