### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by logeen** [logeen/forumweb#20]
**faq_body.tpl** - FAQ: http://www.forumweb.pl/faq.php

**Comment by Drraven** [comment]
Ja się tym mogę zając + stroną konkursu. Z tym, że poczetak jak inny zaczną nazywać elementy (np. menu) i mogę działać.

**Comment by logeen** [comment]
Kiedy zaczniesz pracę, przypisz zadanie na siebie.

**Comment by KacperKozak** [comment]
94f89deee9560c6837f12bbec71edb273085a02f

**Comment by logeen** [comment]
@DeXTeD: Nie możesz weryfikować pracy, którą sam wykonałeś, bo to trochę bez sensu ;) Chyba że to nie Ty ustawiłeś etykietę "weryfikowany" - jeśli tak, to osoba która to zrobiła, powinna przypisać zadanie do siebie.

**Comment by KacperKozak** [comment]
Miałem bardziej na myśli "Do weryfikacji". Ustawianie etykietki na czas tego to trochę IMO bez sensu, ponieważ weryfikacja zmian nie trwa długo.

**Comment by logeen** [comment]
No właśnie może trwać długo, bo trzeba przejrzeć cały kod i przygotować uwagi albo ewentualnie samemu poprawić. Chciałem uniknąć sytuacji, kiedy dwie osoby zaczną weryfikację w tej samej chwili.

Jeśli chcesz wskazać, że zadanie jest do weryfikacji, to po prostu usuń mu wszystkie etykiety i zamknij.
