### ISSUE TITLE
Warunki rejestracji

### ISSUE THREAD

**Issue by logeen** [logeen/forumweb#23]
**agreement.tpl** - warunki rejestracji: http://www.forumweb.pl/profile.php?mode=register

**Comment by Kwpolska** [comment]
"no chyba" = zdecydowac czy article, czy section.

**Comment by Comandeer** [comment]
IMO article. w końcu to jedna rzecz
ja się zastanawiam nad inną rzeczą: czy section w article jest odpowiednie. Ja raczej article widzę tak: header, div (zamiast section), footer.

**Comment by Kwpolska** [comment]
z [Dive into HTML5](http://diveintohtml5.org/semantics.html#new-elements):

> The section element represents a generic document or application section. A section, in this context, is a thematic grouping of content, typically with a heading. Examples of sections would be chapters, the tabbed pages in a tabbed dialog box, or the numbered sections of a thesis. A Web site's home page could be split into sections for an introduction, news items, contact information.

**Comment by Comandeer** [comment]
hmmm... ok, zerknąłem do specki i jest tam nawet przykład artykułu z sekcją w środku :)

**Comment by Comandeer** [comment]
przykład jest identyczny z zastosowanym przez ciebie kodem
