### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by logeen** [logeen/forumweb#3]
**viewforum_body.tpl** - Forum: http://www.forumweb.pl/viewforum.php?f=11

---

UWAGA: Należy zwrócić uwagę, że układ listy tematów forum jest podobny jak układ forów na stronie głównej, a więc kod HTML powinien być spójny do zadania #2

**Comment by KacperKozak** [comment]
1. Breadcrumb do poprawy
2. {topicrow.ROW_ID} jest pusty?
3. Objąć w div.viewforum_body-tpl
