### ISSUE TITLE
Raportuj ten post do moderatora

### ISSUE THREAD

**Issue by logeen** [logeen/forumweb#41]
**report_posting_body.tpl** - Raportuj ten post do moderatora

**Comment by logeen** [comment]
To nie jest semantyczny kod HTML. W tym zadaniu nie chodziło przecież tylko o wyrównanie wcięć w kodzie :)

**Comment by KacperKozak** [comment]
Nie da się podejrzeć

> Not Found
> The requested URL /forumweb/report.php was not found on this server.
