### ISSUE TITLE
"Napisz..." - dodatki

### ISSUE THREAD

**Issue by logeen** [logeen/forumweb#8]
- **posting_preview.tpl** - Podgląd (nowy temat/post)
- **posting_smilies.tpl** - Emotikony: http://www.forumweb.pl/posting.php?mode=smilies
- **posting_poll_body.tpl** - Dodaj Ankietę: http://www.forumweb.pl/posting.php?mode=newtopic&f=11
- **privmsgs_preview.tpl** - Podgląd (prywatna wiadomość): http://www.forumweb.pl/privmsg.php?mode=post

---

Zadanie związane z #7

**Comment by Kwpolska** [comment]
...plus helpline, input name=helpbox.  trzeba wpisać w pliki językowe (których tutaj chyba nie ma).

**Comment by logeen** [comment]
Dopisane w pliku językowym brakujące opisy.
